sudo: false
dist: trusty
language: php
notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: LkHFLwJAqenVshavb3bcG+DfbKuiMYWIgAbsKmypz1Ie7CmNWCGJJroveZjNrm835BdviBK0Ci/gbXXpq5NVy8m3QWBcxCr0bbwMJ5pIZ1tHMqepxy3TrxYRiWvg7aPZBwwmYLBNSaZelLT2Bx0OQlSeopdWQcnG0cBf52UDmY3daCidNdmLrv7Mdt2bzS4dQKe7FZNB1YTXPtoZCpWeiqLoLdbvQ7dIQuOZhoroDVoiH3NQZqOjJmouRba8dfrsVDzf24t7K43xOLp1lEC8Eg/aLJdePcI8+fbsAXwqjuKqVuD3IkxyoAwxKB2lWUOQ0tiDgy4/j2gd035JYFQPUpYhaiW9YWHfchTyG5X6Kr9BKVSmIDXwJfy1n7EwmgRxGSTupSAH6VDZNdTNkHkeceahSCmgncBoh3va8xz1jTYHNVu96At91Lm9qUh0mjApz66TAml+JaX0j/0m7yWqEAil1WQggbKgBVJ9ofcnSx1wEzBsqPHKnFnYtjVBm6gXqtDDzYAnmRNwB72mb0iOY5z5bFmQidxwotFLurvLQZmRZnKOsuGqbWNkvpmt+0EIJdM+1hi4COyVvEIRy6YlbxilJDGRKvtsF+g6xh4cVyRi+3pnvnOGWJPCeeuX9ydYaIV4PyPkO23T4rRNJz6t9Y1fEfNDiYa3Um0FkEKTlfw=
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: WP_VERSION=latest
  - php: 7.2
    env: SNIFF=1
  - php: 7.1
    env: WP_VERSION=latest
  - php: 7.0
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=4.5
  - php: 5.6
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=trunk
  - php: 5.6
    env: SNIFF=1
  - php: 5.3
    env: WP_VERSION=latest
    dist: precise
before_install:
  - |
    if [[ "$SNIFF" == "1" ]]; then
      export PHPCS_DIR=/tmp/phpcs;
      export SNIFFS_DIR=/tmp/sniffs;
      git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR;
      git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git $SNIFFS_DIR/wpcs/;
      git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility/;
      git clone -b master --depth 1 https://github.com/PHPCompatibility/PHPCompatibilityWP.git $SNIFFS_DIR/PHPCompatibilityWP/;
      $PHPCS_DIR/bin/phpcs --config-set installed_paths $SNIFFS_DIR/wpcs/WordPress-Core/,$SNIFFS_DIR/wpcs/WordPress-Docs/,$SNIFFS_DIR/wpcs/WordPress-Extra/,$SNIFFS_DIR/PHPCompatibility/,$SNIFFS_DIR/PHPCompatibilityWP/;
      phpenv rehash;
    fi

before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    composer global require "phpunit/phpunit=4.8.*|5.7.*"
  fi
script:
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    phpunit .
    WP_MULTISITE=1 phpunit .
  fi
- |
  if [[ "$SNIFF" == "1" ]] ; then
    $PHPCS_DIR/bin/phpcs -p . --standard=phpcs.xml
  fi
